# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 26, 14, 17, 21, 302192, tzinfo=utc)),
        ),
    ]
